# Secret contenant les credentials Postgres.
# En prod on utilise Sealed Secrets ou un Vault. Ici stringData pour la clarté.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: boutique_user
  POSTGRES_PASSWORD: boutique_pwd_change_me
  POSTGRES_DB: boutiquedb
